-- Create user_favorites table
create table if not exists user_favorites (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  tip_id uuid references tips(id) not null,
  created_at timestamptz default now(),
  unique (user_id, tip_id)
);

-- Enable RLS
alter table user_favorites enable row level security;

-- Policies
create policy "Users can view their own favorites"
  on user_favorites for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own favorites"
  on user_favorites for insert
  with check ( auth.uid() = user_id );

create policy "Users can delete their own favorites"
  on user_favorites for delete
  using ( auth.uid() = user_id );
